export enum Permissions {
  // Usuario
  LISTAR_USUARIOS = "LISTAR_USUARIOS",
  ELIMINAR_USUARIO = "ELIMINAR_USUARIO",
  QUITAR_ROL = "QUITAR_ROL",

  // Cliente
  LISTAR_CLIENTES = "LISTAR_CLIENTES",
  OBTENER_CLIENTE = "OBTENER_CLIENTE",
  CREAR_CLIENTE = "CREAR_CLIENTE",
  EDITAR_CLIENTE = "EDITAR_CLIENTE",
  ELIMINAR_CLIENTE = "ELIMINAR_CLIENTE",

  //Detalle de venta
  LISTAR_DETALLE_VENTAS = "LISTAR_DETALLE_VENTAS",
  OBTENER_DETALLE_VENTA = "OBTENER_DETALLE_VENTA",
  CREAR_DETALLE_VENTA = "CREAR_DETALLE_VENTA",
  EDITAR_DETALLE_VENTA = "EDITAR_DETALLE_VENTA",
  ELIMINAR_DETALLE_VENTA = "ELIMINAR_DETALLE_VENTA",

  // Forma de pago
  LISTAR_FORMA_PAGO = "LISTAR_FORMA_PAGO",
  OBTENER_FORMA_PAGO = "OBTENER_FORMA_PAGO",
  CREAR_FORMA_PAGO = "CREAR_FORMA_PAGO",
  EDITAR_FORMA_PAGO = "EDITAR_FORMA_PAGO",
  ELIMINAR_FORMA_PAGO = "ELIMINAR_FORMA_PAGO",

  // Linea
  LISTAR_LINEAS = "LISTAR_LINEAS",
  OBTENER_LINEA = "OBTENER_LINEA",
  CREAR_LINEA = "CREAR_LINEA",
  EDITAR_LINEA = "EDITAR_LINEA",
  ELIMINAR_LINEA = "ELIMINAR_LINEA",

  // Marca
  LISTAR_MARCAS = "LISTAR_MARCAS",
  OBTENER_MARCA = "OBTENER_MARCA",
  CREAR_MARCA = "CREAR_MARCA",
  EDITAR_MARCA = "EDITAR_MARCA",
  ELIMINAR_MARCA = "ELIMINAR_MARCA",

  // Producto
  LISTAR_PRODUCTOS = "LISTAR_PRODUCTOS",
  OBTENER_PRODUCTO = "OBTENER_PRODUCTO",
  CREAR_PRODUCTO = "CREAR_PRODUCTO",
  EDITAR_PRODUCTO = "EDITAR_PRODUCTO",
  ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO",

  // Proveedor
  LISTAR_PROVEEDORES = "LISTAR_PROVEEDORES",
  OBTENER_PROVEEDOR = "OBTENER_PROVEEDOR",
  CREAR_PROVEEDOR = "CREAR_PROVEEDOR",
  EDITAR_PROVEEDOR = "EDITAR_PROVEEDOR",
  ELIMINAR_PROVEEDOR = "ELIMINAR_PROVEEDOR",

  // Tipo de documento
  LISTAR_TIPOS_DOCUMENTO = "LISTAR_TIPOS_DOCUMENTO",
  OBTENER_TIPO_DOCUMENTO = "OBTENER_TIPO_DOCUMENTO",
  CREAR_TIPO_DOCUMENTO = "CREAR_TIPO_DOCUMENTO",
  EDITAR_TIPO_DOCUMENTO = "EDITAR_TIPO_DOCUMENTO",
  ELIMINAR_TIPO_DOCUMENTO = "ELIMINAR_TIPO_DOCUMENTO",

  // Venta
  LISTAR_VENTAS = "LISTAR_VENTAS",
  OBTENER_VENTA = "OBTENER_VENTA",
  CREAR_VENTA = "CREAR_VENTA",
  EDITAR_VENTA = "EDITAR_VENTA",
  ELIMINAR_VENTA = "ELIMINAR_VENTA",
}
